### PR TITLE
Keyword Completion

### LINKED ISSUE #11: Server - Add completion for keywords in a schema
When creating a property inside a schema, suggest dialect appropriate keywords for auto-completion.

* [ ] Suggestions should only appear in a schema context. (Ex: The value of the `properties` keyword is an object, but it's not a schema and shouldn't suggest keywords.)
* [ ] Only suggest keywords appropriate for the for current dialect. (Ex: Don't suggest `definitions` in 2020-12.) (Hint: Use `@hyperjump/json-schema` to determine what keywords are appropriate for each dialect.)
* [ ] Be sure to correctly handle embedded schemas where the dialect changes.

### PR DESCRIPTION
**Pull request by diyaayay**
Resolves #11 

image
image

### CODE REVIEW

**Comment by diyaayay** [comment]
The checks fail because changes are made to `node_modules` exposing `getDialect` locally.

**Review by jdesrosiers — CHANGES_REQUESTED** [review]
This solution only works if `$schema` is present. That's not good enough. Not all schemas will have `$schema`. The dialect might be set in the settings, or it might be a subschema or embedded schema.

I don't think there's a good way to get the schema's dialect from the node, which makes it hard to get around this problem. However, an update I'm working on fixes that problem. So, maybe we put this PR into "draft" status until my change is merged. Then we can solve this problem easily.

But, that won't solve the whole problem. There's also no good way to know if the node is schema and these completions should only show up if the node is a schema. I know that's a problem and have plans to address it, but I don't have a solution yet. So, again, maybe we don't have a sufficient foundation to add this functionality yet and we should put it on hold for now.

**Comment by jdesrosiers** [comment]
I rebased to get the refactoring changes.

**Comment by jdesrosiers** [comment]
> I don't think there's a good way to get the schema's dialect from the node, which makes it hard to get around this problem. However, an update I'm working on fixes that problem. So, maybe we put this PR into "draft" status until my change is merged. Then we can solve this problem easily.

With the refactor, we can now solve this problem. The node now has the `dialectUri` property so we don't need to rely on the `$schema` keyword (that might not be there). We can provide the keyword completion if the found node is an object, but we still need a way to restrict that to only objects that are schemas.

**Review by jdesrosiers — APPROVED** [review]

**Pull request merged**
