### PR TITLE
Completion of if/then patterns for every if nested in blocks

### LINKED ISSUE #12: Server - Completion for if/then patterns
The server should detect when the user uses the `if` keyword and propose several completions for common patterns.

This is the most common pattern.

```json
{
  "if": {
    "type": "object",
    "properties": {
      "{varName}": { "const": "{value}" }
    },
    "required": ["{varName}"]
  },
  "then": {
    ...
  }
}
```

### PR DESCRIPTION
**Pull request by diyaayay**
Resolves #12 

using `currentProperty` does not for now recognize "if" in nested blocks. So, the current approach could be changed accordingly which identifies "if" at all positions.

image
WhatsApp Image 2024-06-01 at 15 01 59_645d4a0f

### CODE REVIEW

**Review by jdesrosiers — COMMENTED** [review]
The `completion.js` file is going to get huge as we add more and more completions. Is there a way we can separate the `$schema` completion and the `if` completion? I think we should be able to do something similar to what we're doing for diagnostics using the pubsub pattern.

**Comment by diyaayay** [comment]
> The `completion.js` file is going to get huge as we add more and more completions. Is there a way we can separate the `$schema` completion and the `if` completion? I think we should be able to do something similar to what we're doing for diagnostics using the pubsub pattern.

Right, I've tried to do it the way diagnostics are handled in `deprecated.js` and `validation-errors.js`

**Comment by jdesrosiers** [comment]
That force-push was just me rebasing on top of the refactor that I just pushed. The only change was the usage of `findNodeByOffset`.

**Comment by jdesrosiers** [comment]
I rebased to get dependency updates to and get the change from https://github.com/hyperjump-io/json-schema/pull/65

At this point I think we just need to remove the comments and get the indentation/formatting of the completion string to look right.

**Comment by jdesrosiers** [comment]
I found the [Snippet Syntax](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) that allows us to define tab completion functionality for this snippet.

**Comment by jdesrosiers** [comment]
I removed the `true`/`false` completion options. That kind of completion option applies for any location that accepts a schema, so I'd like to address that separately.

**Comment by diyaayay** [comment]
> I removed the `true`/`false` completion options. That kind of completion option applies for any location that accepts a schema, so I'd like to address that separately.

Right, makes more sense. I should've kept that in mind.

**Pull request merged**
